import Head from "next/head";
import Image from "next/image";
import {useState, useEffect} from "react";
import styles from "@/styles/Home.module.css";

import dynamic from "next/dynamic";

export default function Home() {
  const DynamicEditor = dynamic(() => import("../components/EditorModule"), {
    ssr: false,
  });

  const [isEditorReady, setIsEditorReady] = useState(false);

  useEffect(() => {
    setIsEditorReady(true);
  }, []);

  return (
    <>
      <Head>
        <title>집패스 어드민 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {isEditorReady ? (
          <DynamicEditor isEditorReady={isEditorReady} />
        ) : (
          <p>불러오는중.. </p>
        )}
      </div>
    </>
  );
}
